name:                puffin
version:             0.1.0.0
github:              "Kove-W-O-Salter/puffin"
license:             BSD3
author:              "Kove W. Ochre-Salter"
maintainer:          "kove.w.o.salter@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Kove-W-O-Salter/puffin#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- directory

library:
  source-dirs: src

executables:
  puffin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - puffin

tests:
  puffin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - puffin
